name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn install

      - run: GH_TOKEN=${{ secrets.GH_TOKEN }} GIST_ID=${{ secrets.GIST_ID }} yarn execute
